name: hello-runner
on:
  workflow_dispatch:
jobs:
  hello:
    runs-on: [self-hosted, openstack]
    steps:
      - run: |
          echo "Bonjour depuis $(hostname)"
          whoami
          openstack --version
